<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Qowaiv.CodeAnalysis</RootNamespace>
    <OutputType>library</OutputType>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Pack/Properties/ProductInfo.cs" Link="Properties/ProductInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
